services:
  ollama:
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_IGPU_ENABLE=1
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd

  ollama-init:
    build:
      target: vulkan
