services:
  ollama:
    build:
      context: ./Dockerfile.d/ollama
      args:
        - OLLAMA_PORT=${OLLAMA_PORT}
        - OLLAMA_BASE_IMAGE=ollama/ollama:latest
    container_name: symbiosis_ollama
    ports:
      - "127.0.0.1:${OLLAMA_PORT}:${OLLAMA_PORT}"
    environment:
      - OLLAMA_HOST=0.0.0.0:${OLLAMA_PORT}
    volumes:
      - symbiosis_ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  # Installs models
  ollama-init:
    build:
      context: ./Dockerfile.d/ollama-init
      dockerfile: Dockerfile
      target: cpu
    container_name: symbiosis_ollama_init
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_PORT=${OLLAMA_PORT}
    profiles:
      - manual
    volumes:
      - ./Dockerfile.d/ollama-init/output:/output
    restart: "no"

volumes:
  symbiosis_ollama_data: